### PR TITLE
Rename MICROPY_HW_HAS_SDCARD to MICROPY_HW_ENABLE_SDCARD

### PR DESCRIPTION
**Pull request by mcauser**
https://github.com/micropython/micropython/commit/9670b2652649c674e580e039a4fe8e8e885b44fc

### CODE REVIEW

**Comment by SpotlightKid** [comment]
@mcauser Thanks for the PR and keeping a lookout for changes in upstream MicroPython.

I have to admit. I'm not doing much with MicroPython these days. Are you interested in transferring ownership of this repo to you? Or we could set up a Github org to host all "extra" board definitions where we could share maintainership.

**Review by SpotlightKid — APPROVED** [review]
LGTM

**Comment by mcauser** [comment]
Hi, I'm happy with either transferring ownership or making a boards github org. It's stm32 specific, so maybe "micropython-stm32-boards". Bit of a mouthful... Maybe worry about that later and I'll add you as an admin then if you're still keen.

**Comment by SpotlightKid** [comment]
I suggest transferring the repo to you and you can set up a github org as you like and in your own time, to which you can add me later, if necessary.

**Pull request merged**
